#!/usr/bin/env python

# Copyright L. Easy, F. Militello, T. Nicholas, J. Omotani, F. Riva, N.
# Walkden, UKAEA, 2017, 2018
# email: fulvio.militello@ukaea.uk
#
# This file is part of the STORM module of BOUT++.
#
# STORM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# STORM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with STORM.  If not, see <https://www.gnu.org/licenses/>.

#from boututils import shell, launch, getmpirun
from boutdata import collect
from scipy import io as sio
import numpy as np
import os
import shutil
    
os.chdir('data')

    #Read in Data
t = collect('t_array')
n    = collect('n',    yguards = True)
T    = collect('T',    yguards = True)
phi  = collect('phi',  yguards = True)
vort = collect('vort', yguards = True)

sio.savemat("matlab_output.mat", mdict={'t':t, 'n':n, 'T':T, 'phi':phi, 'vort':vort})

os.chdir('../')
